name: Build & Publish
on: push

jobs:
  update:
    name: Update docs & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install

      - run: npm run doc
        if: contains(github.ref, 'master')
      - uses: EndBug/add-and-commit@v2
        if: contains(github.ref, 'master')
        with:
          message: "[auto] Update documentation"
          path: docs
          pattern: "*.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run lint
      - uses: EndBug/add-and-commit@v2
        with:
          message: "[auto] Lint source"
          path: src
          pattern: "*.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to NPM & GPR
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: update

    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/version-check@v1
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: echo "Version change! -> ${{ steps.check.outputs.type }}"
      
      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm install

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Node.js for GPR
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com/"
          scope: "@snazzah"

      - name: Set up package for GPR
        if: steps.check.outputs.changed == 'true'
        run: npm run gpr-setup

      - name: Publish package to GPR
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
