name: Update tags and docs for new release
on:
  push:
    paths:
      - .github/workflows/publish-test.yml

jobs:
  publish:
    name: Publish on NPM and GPR
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Node.js for GPR
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com/"
          scope: "@dbots-pkg"

      - name: Set up package for GPR
        run: npm run gpr-setup

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
